name: Build EXE for Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller opencv-python pyautogui pillow keyboard

    - name: Build EXE
      run: |
        pyinstaller src/pigclicker.py --onefile --windowed --icon=assets/pigclicker_icon.ico

    - name: Decode code signing cert
      run: |
        echo "${{ secrets.CODESIGN_CERT }}" | base64 -d > pigclicker.pfx

    - name: Sign the EXE
      run: |
        & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe" sign `
          /f pigclicker.pfx `
          /p "${{ secrets.CODESIGN_PASS }}" `
          /fd sha256 `
          /tr http://timestamp.digicert.com `
          /td sha256 `
          dist\pigclicker.exe

    - name: Verify Signature
      run: |
        & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe" verify /pa dist\pigclicker.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PigClicker-Signed
        path: dist/pigclicker.exe
