
name: Build EXE for Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller pyautogui opencv-python pillow keyboard

      - name: Build EXE
        run: pyinstaller --onefile src/pigclicker.py --name PigClicker-v1.2

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: PigClicker-v1.2
          path: dist/PigClicker-v1.2.exe
